import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { Link } from "react-router";

import { useAuth } from "../auth/useAuth";
import { ApiError, apiRequest } from "../lib/api";
import type { ReportPage, ReportType } from "../lib/types";
import { REPORT_TYPE_LABELS } from "./format";

export function ReportsPage() {
  const { token } = useAuth();
  const [type, setType] = useState<ReportType | "">("");
  const params = new URLSearchParams({ limit: "50" });
  if (type) params.set("report_type", type);
  const reports = useQuery({
    queryKey: ["reports", type],
    queryFn: () => apiRequest<ReportPage>(`/api/v1/reports?${params.toString()}`, { token }),
  });
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-xl font-semibold">Reports</h1>
        <p className="mt-1 text-sm text-slate-600">
          Reports record source documents, extracted values with evidence, rule results, the AI analysis and every
          human decision as of a point in time. Each is rendered from a stored snapshot and fingerprinted (SHA-256), so
          it can be verified later. Generate one from a document, a comparison or an investigation.
        </p>
      </div>
      <select
        aria-label="Report type"
        value={type}
        onChange={(event) => {
          setType(event.target.value as ReportType | "");
        }}
        className="rounded-md border border-slate-300 bg-white px-2 py-1.5 text-sm"
      >
        <option value="">All report types</option>
        {(Object.keys(REPORT_TYPE_LABELS) as ReportType[]).map((value) => (
          <option key={value} value={value}>
            {REPORT_TYPE_LABELS[value]}
          </option>
        ))}
      </select>
      <section aria-label="Report list" className="rounded-xl border border-slate-200 bg-white">
        {reports.isPending ? (
          <p className="p-5 text-sm text-slate-500">Loading…</p>
        ) : reports.isError ? (
          <p role="alert" className="p-5 text-sm text-red-700">
            {reports.error instanceof ApiError
              ? (reports.error.problem?.detail ?? reports.error.message)
              : "The reports could not be loaded."}
          </p>
        ) : reports.data.items.length === 0 ? (
          <p className="p-5 text-sm text-slate-500">No report yet.</p>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm">
              <thead className="border-b border-slate-200 text-xs uppercase text-slate-500">
                <tr>
                  <th className="px-5 py-2 font-medium">Report</th>
                  <th className="py-2 font-medium">Type</th>
                  <th className="py-2 font-medium">Data as of</th>
                  <th className="py-2 pr-5 font-medium">Generated by</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {reports.data.items.map((item) => (
                  <tr key={item.id}>
                    <td className="px-5 py-2.5">
                      <Link to={`/reports/${item.id}`} className="font-medium text-blue-900 hover:underline">
                        {item.title}
                      </Link>
                      {item.workflow_id && <span className="block text-xs text-slate-500">from a workflow</span>}
                    </td>
                    <td className="py-2.5">{REPORT_TYPE_LABELS[item.report_type]}</td>
                    <td className="py-2.5 text-slate-600">{new Date(item.as_of).toLocaleString()}</td>
                    <td className="py-2.5 pr-5 text-slate-600">{item.generated_by_email}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </section>
    </div>
  );
}
