import { useMutation, useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { Link, useParams } from "react-router";

import { useAuth } from "../auth/useAuth";
import { ApiError, apiRequest, downloadFile } from "../lib/api";
import type { Report, ReportVerification } from "../lib/types";
import { REPORT_TYPE_LABELS } from "./format";

function errorText(error: unknown): string {
  return error instanceof ApiError ? (error.problem?.detail ?? error.message) : "The request failed.";
}

export function ReportPage() {
  const { reportId } = useParams();
  const { token } = useAuth();
  const [downloadError, setDownloadError] = useState<string | null>(null);
  const report = useQuery({
    queryKey: ["report", reportId],
    queryFn: () => apiRequest<Report>(`/api/v1/reports/${reportId ?? ""}`, { token }),
  });
  const verify = useMutation({
    mutationFn: () =>
      apiRequest<ReportVerification>(`/api/v1/reports/${reportId ?? ""}/verify`, { method: "POST", token }),
  });
  if (report.error) {
    return (
      <p role="alert" className="text-sm text-red-700">
        {errorText(report.error)}
      </p>
    );
  }
  if (!report.data) return <p className="text-sm text-slate-500">Loading…</p>;
  const data = report.data;
  const download = (format: "md" | "json") => {
    setDownloadError(null);
    downloadFile(`/api/v1/reports/${data.id}/download?format=${format}`, token, `report.${format}`).catch(
      (error: unknown) => {
        setDownloadError(errorText(error));
      },
    );
  };
  return (
    <div className="space-y-5">
      <div>
        <Link to="/reports" className="text-sm text-blue-900 hover:underline">
          ← Reports
        </Link>
        <h1 className="mt-1 text-xl font-semibold">{data.title}</h1>
        <p className="mt-1 text-sm text-slate-600">
          {REPORT_TYPE_LABELS[data.report_type]} · data as of {new Date(data.as_of).toLocaleString()} · generated by{" "}
          {data.generated_by_email} on {new Date(data.created_at).toLocaleString()}
          {data.workflow_id && (
            <>
              {" · "}
              <Link to={`/workflows/${data.workflow_id}`} className="text-blue-900 hover:underline">
                workflow
              </Link>
            </>
          )}
        </p>
        <p className="mt-1 break-all font-mono text-xs text-slate-500">SHA-256 {data.content_sha256}</p>
      </div>
      <div className="flex flex-wrap items-center gap-2">
        <button
          type="button"
          onClick={() => {
            download("md");
          }}
          className="rounded-md bg-blue-900 px-3 py-1.5 text-sm font-medium text-white hover:bg-blue-800"
        >
          Download (Markdown)
        </button>
        <button
          type="button"
          onClick={() => {
            download("json");
          }}
          className="rounded-md border border-slate-300 px-3 py-1.5 text-sm hover:bg-slate-100"
        >
          Download snapshot (JSON)
        </button>
        <button
          type="button"
          onClick={() => {
            verify.mutate();
          }}
          className="rounded-md border border-slate-300 px-3 py-1.5 text-sm hover:bg-slate-100"
        >
          Verify
        </button>
        {verify.data && (
          <span
            role="status"
            className={`rounded px-2 py-0.5 text-xs ${
              verify.data.matches ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-red-700"
            }`}
          >
            {verify.data.matches
              ? "Verified: the stored snapshot renders to exactly this report."
              : "Mismatch: the stored report differs from its snapshot."}
          </span>
        )}
      </div>
      {(downloadError ?? verify.error) && (
        <p role="alert" className="text-sm text-red-700">
          {downloadError ?? errorText(verify.error)}
        </p>
      )}
      {/* Shown as text: report content comes from documents and is never rendered as HTML. */}
      <pre
        aria-label="Report content"
        className="overflow-x-auto whitespace-pre-wrap rounded-xl border border-slate-200 bg-white p-5 font-mono text-xs leading-relaxed text-slate-800"
      >
        {data.content}
      </pre>
    </div>
  );
}
