"""DocumentStorage abstraction (Module 2).

Object keys are always generated by the server (never derived from user filenames) and are
validated again by every backend - defence in depth against path traversal.
"""

from __future__ import annotations

import re
import uuid
from collections.abc import AsyncIterator
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Protocol, runtime_checkable

from docintel.core.config import StorageBackendName

DEFAULT_CHUNK_SIZE = 64 * 1024
_KEY_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._/-]{0,511}$")


class StorageError(Exception):
    """Base class for storage failures."""

    retryable: bool = False


class StorageKeyError(StorageError, ValueError):
    """The object key is malformed or would escape the storage root."""


class ObjectNotFoundError(StorageError):
    """No object exists under the key."""


class StorageUnavailableError(StorageError):
    """Transient backend failure (network, throttling, 5xx)."""

    retryable = True


def validate_key(key: str) -> str:
    if not _KEY_PATTERN.fullmatch(key):
        msg = f"invalid storage key: {key!r}"
        raise StorageKeyError(msg)
    segments = key.split("/")
    if any(segment in ("", ".", "..") for segment in segments):
        msg = f"invalid storage key segment in {key!r}"
        raise StorageKeyError(msg)
    return key


def _check_extension(extension: str) -> str:
    if not re.fullmatch(r"[a-z0-9]{1,8}", extension):
        msg = f"invalid extension for storage key: {extension!r}"
        raise StorageKeyError(msg)
    return extension


def document_object_key(document_id: uuid.UUID, version_number: int, extension: str) -> str:
    """Canonical key for an uploaded file: never contains user-controlled text."""
    _check_extension(extension)
    return validate_key(f"documents/{document_id}/v{version_number}/original.{extension}")


def knowledge_object_key(knowledge_document_id: uuid.UUID, extension: str) -> str:
    """Key of a knowledge base file (each version is its own knowledge document)."""
    _check_extension(extension)
    return validate_key(f"knowledge/{knowledge_document_id}/original.{extension}")


def page_preview_key(document_id: uuid.UUID, version_number: int, page_number: int) -> str:
    """Key of a rendered page preview (PNG) for one document version."""
    return validate_key(f"documents/{document_id}/v{version_number}/pages/{page_number:04d}.png")


@dataclass(frozen=True, slots=True)
class StoredObject:
    key: str
    size_bytes: int


@dataclass(frozen=True, slots=True)
class ListedObject:
    key: str
    size_bytes: int
    modified_at: datetime  # timezone-aware (UTC)


@runtime_checkable
class DocumentStorage(Protocol):
    @property
    def backend(self) -> StorageBackendName: ...

    async def put_file(self, key: str, source: Path, *, content_type: str) -> StoredObject:
        """Store the file at `source` under `key` (overwrites atomically)."""
        ...

    def open_stream(
        self, key: str, *, chunk_size: int = DEFAULT_CHUNK_SIZE
    ) -> AsyncIterator[bytes]:
        """Yield the object's bytes. Raises ObjectNotFoundError if missing."""
        ...

    async def download_to(self, key: str, destination: Path) -> None: ...

    async def delete(self, key: str) -> None:
        """Remove the object; deleting a missing object is not an error."""
        ...

    async def exists(self, key: str) -> bool: ...

    def list_objects(self, prefix: str) -> AsyncIterator[ListedObject]:
        """Every stored object whose key starts with `prefix` ("documents/"), in no set order.

        Used by storage reconciliation; files still being written are not listed.
        """
        ...
