"""ORM models. Importing this package registers every table on `Base.metadata`."""

from docintel.db.models.audit import ActorType, AuditLog, AuditOutcome
from docintel.db.models.documents import (
    Document,
    DocumentSource,
    DocumentStatus,
    DocumentType,
    DocumentVersion,
    JobStatus,
    JobType,
    ProcessingJob,
    Sensitivity,
)
from docintel.db.models.extraction import (
    DocumentExtraction,
    EvidenceStatusValue,
    ExtractedField,
    ExtractionMethodUsed,
    ExtractionStatus,
    FieldOrigin,
    LLMCall,
    LLMCallStatus,
    ReviewLevelValue,
    Vendor,
)
from docintel.db.models.identity import Department, Role, User
from docintel.db.models.understanding import (
    ClassificationMethod,
    DocumentClassification,
    DocumentPage,
    DocumentTable,
    ExtractionMethod,
    ReviewReason,
    TableMethod,
    TableRow,
)

__all__ = [
    "ActorType",
    "AuditLog",
    "AuditOutcome",
    "ClassificationMethod",
    "Department",
    "Document",
    "DocumentClassification",
    "DocumentExtraction",
    "DocumentPage",
    "DocumentSource",
    "DocumentStatus",
    "DocumentTable",
    "DocumentType",
    "DocumentVersion",
    "EvidenceStatusValue",
    "ExtractedField",
    "ExtractionMethod",
    "ExtractionMethodUsed",
    "ExtractionStatus",
    "FieldOrigin",
    "JobStatus",
    "JobType",
    "LLMCall",
    "LLMCallStatus",
    "ProcessingJob",
    "ReviewLevelValue",
    "ReviewReason",
    "Role",
    "Sensitivity",
    "TableMethod",
    "TableRow",
    "User",
    "Vendor",
]
